channels:
        - conda-forge
        - rdkit
dependencies:
        - rdkit=2020.09.1.0
        - ipython=7.25.0
        - ipywidgets=7.6.3
        - ipympl=0.7.0
        - numpy=1.20.3
        - openbabel=2.4.1
        - nglview=3.0.3
        - mplcursors=0.4
        - voila=0.2.10